;;; generated file
(define-module (gnu packages stackage ghc-8.8 stage026)
  #:use-module ((guix download))
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module ((guix packages)))
;;; see commit 1597613488
(define license (@@ (guix licenses) license))
;;; explicitly define which ghc to use
(define ghc (@ (gnu packages haskell) ghc-8.8))
;;; add another patch file location (see gnu/packages.scm for pretty original)
(define-syntax-rule (search-patches file-name ...)
 (parameterize
  (((@ (gnu packages) %patch-path) (map (lambda (directory) (string-append directory "/patches")) %load-path)))
  (list ((@@ (gnu packages) search-patch) file-name) ...)))
(define-public haskell-8.8-taffybar
  (package
    (name "haskell-8.8-taffybar")
    (version "3.2.2")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/taffybar/taffybar-" version
                    ".tar.gz"))
              (sha256
               (base32
                "02b6rmsb89c1h7fr81ljbij30pnl8z4dz6xz367g7a2b9hwq42gz"))))
    (properties `((upstream-name . "taffybar") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #t
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)
       #:cabal-revision
       ("1" "0284vnzvgpjjh95p67k2b5476npa52hs8g55fvlvlcx487zpc1sc")))
    (outputs (list "out" "static" "doc"))
    (inputs (list (@ (gnu packages gtk) gtk+)
                  (@ (gnu packages stackage ghc-8.8 stage005)
                     haskell-8.8-ConfigFile)
                  (@ (gnu packages stackage ghc-8.8 stage003)
                     haskell-8.8-HStringTemplate)
                  (@ (gnu packages stackage ghc-8.8 stage006) haskell-8.8-X11)
                  (@ (gnu packages stackage ghc-8.8 stage001)
                     haskell-8.8-ansi-terminal)
                  (@ (gnu packages stackage ghc-8.8 stage001)
                     haskell-8.8-broadcast-chan)
                  (@ (gnu packages stackage ghc-8.8 stage017) haskell-8.8-dbus)
                  (@ (gnu packages stackage ghc-8.8 stage018)
                     haskell-8.8-dbus-hslogger)
                  (@ (gnu packages stackage ghc-8.8 stage001) haskell-8.8-dyre)
                  (@ (gnu packages stackage ghc-8.8 stage012)
                     haskell-8.8-either)
                  (@ (gnu packages stackage ghc-8.8 stage007)
                     haskell-8.8-enclosed-exceptions)
                  (@ (gnu packages stackage ghc-8.8 stage018)
                     haskell-8.8-gi-cairo)
                  (@ (gnu packages stackage ghc-8.8 stage019)
                     haskell-8.8-gi-cairo-connector)
                  (@ (gnu packages stackage ghc-8.8 stage005)
                     haskell-8.8-gi-cairo-render)
                  (@ (gnu packages stackage ghc-8.8 stage022)
                     haskell-8.8-gi-gdk)
                  (@ (gnu packages stackage ghc-8.8 stage021)
                     haskell-8.8-gi-gdkpixbuf)
                  (@ (gnu packages stackage ghc-8.8 stage023)
                     haskell-8.8-gi-gdkx11)
                  (@ (gnu packages stackage ghc-8.8 stage018)
                     haskell-8.8-gi-glib)
                  (@ (gnu packages stackage ghc-8.8 stage023)
                     haskell-8.8-gi-gtk)
                  (@ (gnu packages stackage ghc-8.8 stage024)
                     haskell-8.8-gi-gtk-hs)
                  (@ (gnu packages stackage ghc-8.8 stage020)
                     haskell-8.8-gi-pango)
                  (@ (gnu packages stackage ghc-8.8 stage025)
                     haskell-8.8-gtk-sni-tray)
                  (@ (gnu packages stackage ghc-8.8 stage024)
                     haskell-8.8-gtk-strut)
                  (@ (gnu packages stackage ghc-8.8 stage017)
                     haskell-8.8-haskell-gi)
                  (@ (gnu packages stackage ghc-8.8 stage001)
                     haskell-8.8-haskell-gi-base)
                  (@ (gnu packages stackage ghc-8.8 stage003)
                     haskell-8.8-hslogger)
                  (@ (gnu packages stackage ghc-8.8 stage015)
                     haskell-8.8-http-client)
                  (@ (gnu packages stackage ghc-8.8 stage016)
                     haskell-8.8-http-client-tls)
                  (@ (gnu packages stackage ghc-8.8 stage014)
                     haskell-8.8-http-types)
                  (@ (gnu packages stackage ghc-8.8 stage000)
                     haskell-8.8-multimap)
                  (@ (gnu packages stackage ghc-8.8 stage000)
                     haskell-8.8-old-locale)
                  (@ (gnu packages stackage ghc-8.8 stage003)
                     haskell-8.8-optparse-applicative)
                  (@ (gnu packages stackage ghc-8.8 stage001)
                     haskell-8.8-rate-limit)
                  (@ (gnu packages stackage ghc-8.8 stage002)
                     haskell-8.8-regex-compat)
                  (@ (gnu packages stackage ghc-8.8 stage003) haskell-8.8-safe)
                  (@ (gnu packages stackage ghc-8.8 stage019)
                     haskell-8.8-scotty)
                  (@ (gnu packages stackage ghc-8.8 stage003)
                     haskell-8.8-split)
                  (@ (gnu packages stackage ghc-8.8 stage019)
                     haskell-8.8-status-notifier-item)
                  (@ (gnu packages stackage ghc-8.8 stage000)
                     haskell-8.8-time-locale-compat)
                  (@ (gnu packages stackage ghc-8.8 stage000)
                     haskell-8.8-time-units)
                  (@ (gnu packages stackage ghc-8.8 stage001)
                     haskell-8.8-transformers-base)
                  (@ (gnu packages stackage ghc-8.8 stage001)
                     haskell-8.8-tuple)
                  (@ (gnu packages stackage ghc-8.8 stage000)
                     haskell-8.8-utf8-string)
                  (@ (gnu packages stackage ghc-8.8 stage000)
                     haskell-8.8-xdg-basedir)
                  (@ (gnu packages stackage ghc-8.8 stage013)
                     haskell-8.8-xdg-desktop-entry)
                  (@ (gnu packages stackage ghc-8.8 stage000) haskell-8.8-xml)
                  (@ (gnu packages stackage ghc-8.8 stage001)
                     haskell-8.8-xml-helpers)
                  (@ (gnu packages stackage ghc-8.8 stage007)
                     haskell-8.8-xmonad)
                  (@ (gnu packages pkg-config) %pkg-config)))
    (propagated-inputs (list (@ (gnu packages xorg) libpthread-stubs)
                             (@ (gnu packages xorg) libx11)
                             (@ (gnu packages xorg) libxext)
                             (@ (gnu packages xorg) libxinerama)
                             (@ (gnu packages xorg) libxrandr)
                             (@ (gnu packages xorg) libxscrnsaver)
                             (@ (gnu packages compression) zlib)))
    (home-page "http://github.com/taffybar/taffybar")
    (synopsis "A desktop bar similar to xmobar, but with more GUI")
    (description
     "Taffybar is a gtk+3 (through gi-gtk) based desktop information bar, intended
primarily for use with XMonad, though it can also function alongside other EWMH
compliant window managers. It is similar in spirit to xmobar, but it differs in
that it gives up some simplicity for a reasonable helping of eye candy.")
    (license license:bsd-3)))

haskell-8.8-taffybar

