;;; generated file
(define-module (gnu packages stackage ghc-8.4 stage027)
  #:use-module ((guix download))
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module ((guix packages)))
;;; see commit 1597613488
(define license (@@ (guix licenses) license))
;;; explicitly define which ghc to use
(define ghc (@ (gnu packages haskell) ghc-8.4))
;;; add another patch file location (see gnu/packages.scm for pretty original)
(define-syntax-rule (search-patches file-name ...)
 (parameterize
  (((@ (gnu packages) %patch-path) (map (lambda (directory) (string-append directory "/patches")) %load-path)))
  (list ((@@ (gnu packages) search-patch) file-name) ...)))
(define-public haskell-8.4-gi-gtk-hs
  (package
    (name "haskell-8.4-gi-gtk-hs")
    (version "0.3.6.3")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/gi-gtk-hs/gi-gtk-hs-" version
                    ".tar.gz"))
              (sha256
               (base32
                "0xnrssnfaz57akrkgpf1cm3d4lg3cmlh0b8yp6w9pdsbp0lld2ay"))))
    (properties `((upstream-name . "gi-gtk-hs") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #t
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)))
    (outputs (list "out" "doc"))
    (inputs (list (@ (gnu packages stackage ghc-8.4 stage000)
                     haskell-8.4-base-compat)
                  (@ (gnu packages stackage ghc-8.4 stage025)
                     haskell-8.4-gi-gdk)
                  (@ (gnu packages stackage ghc-8.4 stage024)
                     haskell-8.4-gi-gdkpixbuf)
                  (@ (gnu packages stackage ghc-8.4 stage021)
                     haskell-8.4-gi-glib)
                  (@ (gnu packages stackage ghc-8.4 stage022)
                     haskell-8.4-gi-gobject)
                  (@ (gnu packages stackage ghc-8.4 stage026)
                     haskell-8.4-gi-gtk)
                  (@ (gnu packages stackage ghc-8.4 stage001)
                     haskell-8.4-haskell-gi-base)))
    (propagated-inputs (list (@ (gnu packages compression) zlib-1.2.12)))
    (home-page "https://github.com/haskell-gi/gi-gtk-hs")
    (synopsis
     "A wrapper for gi-gtk, adding a few more idiomatic API parts on top")
    (description
     "A wrapper for gi-gtk, adding a few more idiomatic API parts on top")
    (license (license "FSDG-compatible" "LGPL" ""))))

haskell-8.4-gi-gtk-hs

(define-public haskell-8.4-gi-gtksource
  (package
    (name "haskell-8.4-gi-gtksource")
    (version "3.0.16")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/gi-gtksource/gi-gtksource-"
                    version ".tar.gz"))
              (sha256
               (base32
                "0fm5bnyq4f9icyhxkyxf42mmanmc2klbdgin75dcdq5r92gipfcp"))))
    (properties `((upstream-name . "gi-gtksource") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #t
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)))
    (outputs (list "out" "doc"))
    (inputs (list (@ (gnu packages gtk) gtksourceview)
                  (@ (gnu packages stackage ghc-8.4 stage023)
                     haskell-8.4-gi-atk)
                  (@ (gnu packages stackage ghc-8.4 stage021)
                     haskell-8.4-gi-cairo)
                  (@ (gnu packages stackage ghc-8.4 stage025)
                     haskell-8.4-gi-gdk)
                  (@ (gnu packages stackage ghc-8.4 stage024)
                     haskell-8.4-gi-gdkpixbuf)
                  (@ (gnu packages stackage ghc-8.4 stage023)
                     haskell-8.4-gi-gio)
                  (@ (gnu packages stackage ghc-8.4 stage021)
                     haskell-8.4-gi-glib)
                  (@ (gnu packages stackage ghc-8.4 stage022)
                     haskell-8.4-gi-gobject)
                  (@ (gnu packages stackage ghc-8.4 stage026)
                     haskell-8.4-gi-gtk)
                  (@ (gnu packages stackage ghc-8.4 stage023)
                     haskell-8.4-gi-pango)
                  (@ (gnu packages stackage ghc-8.4 stage020)
                     haskell-8.4-haskell-gi)
                  (@ (gnu packages stackage ghc-8.4 stage001)
                     haskell-8.4-haskell-gi-base)
                  (@ (gnu packages stackage ghc-8.4 stage000)
                     haskell-8.4-haskell-gi-overloading)
                  (@ (gnu packages pkg-config) %pkg-config)))
    (propagated-inputs (list (@ (gnu packages compression) zlib-1.2.12)))
    (home-page "https://github.com/haskell-gi/haskell-gi")
    (synopsis "GtkSource bindings")
    (description "Bindings for GtkSource, autogenerated by haskell-gi.")
    (license (license "FSDG-compatible" "LGPL" ""))))

haskell-8.4-gi-gtksource

(define-public haskell-8.4-gi-vte
  (package
    (name "haskell-8.4-gi-vte")
    (version "2.91.19")
    (source (origin
              (method url-fetch)
              (uri (string-append "mirror://hackage/package/gi-vte/gi-vte-"
                                  version ".tar.gz"))
              (sha256
               (base32
                "1hnhidjr7jh7i826lj6kdn264i592sfl5kwvymnpiycmcb37dd4y"))))
    (properties `((upstream-name . "gi-vte") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #t
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)))
    (outputs (list "out" "doc"))
    (inputs (list (@ (gnu packages stackage ghc-8.4 stage023)
                     haskell-8.4-gi-atk)
                  (@ (gnu packages stackage ghc-8.4 stage025)
                     haskell-8.4-gi-gdk)
                  (@ (gnu packages stackage ghc-8.4 stage023)
                     haskell-8.4-gi-gio)
                  (@ (gnu packages stackage ghc-8.4 stage021)
                     haskell-8.4-gi-glib)
                  (@ (gnu packages stackage ghc-8.4 stage022)
                     haskell-8.4-gi-gobject)
                  (@ (gnu packages stackage ghc-8.4 stage026)
                     haskell-8.4-gi-gtk)
                  (@ (gnu packages stackage ghc-8.4 stage023)
                     haskell-8.4-gi-pango)
                  (@ (gnu packages stackage ghc-8.4 stage020)
                     haskell-8.4-haskell-gi)
                  (@ (gnu packages stackage ghc-8.4 stage001)
                     haskell-8.4-haskell-gi-base)
                  (@ (gnu packages stackage ghc-8.4 stage000)
                     haskell-8.4-haskell-gi-overloading)
                  (@ (gnu packages pkg-config) %pkg-config)
                  (@ (gnu packages gnome) vte)))
    (propagated-inputs (list (@ (gnu packages compression) zlib-1.2.12)))
    (home-page "https://github.com/haskell-gi/haskell-gi")
    (synopsis "Vte bindings")
    (description "Bindings for Vte, autogenerated by haskell-gi.")
    (license (license "FSDG-compatible" "LGPL" ""))))

haskell-8.4-gi-vte

(define-public haskell-8.4-yesod-recaptcha2
  (package
    (name "haskell-8.4-yesod-recaptcha2")
    (version "0.2.4")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/yesod-recaptcha2/yesod-recaptcha2-"
                    version ".tar.gz"))
              (sha256
               (base32
                "1aw104i2v9m6dc5z5iqzihjfybfxg90l0rj0pazb672qzp9yqj18"))))
    (properties `((upstream-name . "yesod-recaptcha2") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #t
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)))
    (outputs (list "out" "doc"))
    (inputs (list (@ (gnu packages stackage ghc-8.4 stage026)
                     haskell-8.4-classy-prelude-yesod)
                  (@ (gnu packages stackage ghc-8.4 stage021)
                     haskell-8.4-http-conduit)
                  (@ (gnu packages stackage ghc-8.4 stage025)
                     haskell-8.4-yesod-auth)))
    (propagated-inputs (list (@ (gnu packages xorg) libpthread-stubs)
                             (@ (gnu packages compression) zlib-1.2.12)))
    (home-page "https://github.com/ncaq/yesod-recaptcha2#readme")
    (synopsis "yesod recaptcha2")
    (description "recaptcha2 for yesod-form")
    (license license:expat)))

haskell-8.4-yesod-recaptcha2

