;;; generated file
(define-module (gnu packages stackage ghc-8.10 stage025)
  #:use-module ((guix download))
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module ((guix packages)))
;;; see commit 1597613488
(define license (@@ (guix licenses) license))
;;; explicitly define which ghc to use
(define ghc (@ (gnu packages haskell) ghc-8.10))
;;; add another patch file location (see gnu/packages.scm for pretty original)
(define-syntax-rule (search-patches file-name ...)
 (parameterize
  (((@ (gnu packages) %patch-path) (map (lambda (directory) (string-append directory "/patches")) %load-path)))
  (list ((@@ (gnu packages) search-patch) file-name) ...)))
(define-public haskell-8.10-gi-gdkx11
  (package
    (name "haskell-8.10-gi-gdkx11")
    (version "3.0.11")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/gi-gdkx11/gi-gdkx11-" version
                    ".tar.gz"))
              (sha256
               (base32
                "07r47fpx6rvsahgnv8g741fl6h1s6y1xrlyacbpc3d8cv7x4aax2"))))
    (properties `((upstream-name . "gi-gdkx11") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #t
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)))
    (outputs (list "out" "static" "doc"))
    (inputs (list (@ (gnu packages gtk) gdk-pixbuf)
                  (@ (gnu packages stackage ghc-8.10 stage020)
                     haskell-8.10-gi-cairo)
                  (@ (gnu packages stackage ghc-8.10 stage024)
                     haskell-8.10-gi-gdk)
                  (@ (gnu packages stackage ghc-8.10 stage022)
                     haskell-8.10-gi-gio)
                  (@ (gnu packages stackage ghc-8.10 stage021)
                     haskell-8.10-gi-gobject)
                  (@ (gnu packages stackage ghc-8.10 stage020)
                     haskell-8.10-gi-xlib)
                  (@ (gnu packages stackage ghc-8.10 stage019)
                     haskell-8.10-haskell-gi)
                  (@ (gnu packages stackage ghc-8.10 stage006)
                     haskell-8.10-haskell-gi-base)
                  (@ (gnu packages stackage ghc-8.10 stage000)
                     haskell-8.10-haskell-gi-overloading)
                  (@ (gnu packages pkg-config) %pkg-config)))
    (propagated-inputs (list (@ (gnu packages pcre) pcre)
                             (@ (gnu packages compression) zlib)))
    (home-page "https://github.com/haskell-gi/haskell-gi")
    (synopsis "GdkX11 bindings")
    (description "Bindings for GdkX11, autogenerated by haskell-gi.")
    (license (license "FSDG-compatible" "LGPL" ""))))

haskell-8.10-gi-gdkx11

(define-public haskell-8.10-gi-gtk
  (package
    (name "haskell-8.10-gi-gtk")
    (version "3.0.37")
    (source (origin
              (method url-fetch)
              (uri (string-append "mirror://hackage/package/gi-gtk/gi-gtk-"
                                  version ".tar.gz"))
              (sha256
               (base32
                "1psg789lrpcnrwh1y80y7s09hcxl3hihi0gwsmd7j3v731dp7a0k"))))
    (properties `((upstream-name . "gi-gtk") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #t
       #:haskell ,ghc
       #:haddock? #f
       #:configure-flags (list)))
    (outputs (list "out" "static"))
    (inputs (list (@ (gnu packages gtk) gtk+)
                  (@ (gnu packages stackage ghc-8.10 stage022)
                     haskell-8.10-gi-atk)
                  (@ (gnu packages stackage ghc-8.10 stage020)
                     haskell-8.10-gi-cairo)
                  (@ (gnu packages stackage ghc-8.10 stage024)
                     haskell-8.10-gi-gdk)
                  (@ (gnu packages stackage ghc-8.10 stage023)
                     haskell-8.10-gi-gdkpixbuf)
                  (@ (gnu packages stackage ghc-8.10 stage022)
                     haskell-8.10-gi-gio)
                  (@ (gnu packages stackage ghc-8.10 stage020)
                     haskell-8.10-gi-glib)
                  (@ (gnu packages stackage ghc-8.10 stage021)
                     haskell-8.10-gi-gobject)
                  (@ (gnu packages stackage ghc-8.10 stage023)
                     haskell-8.10-gi-pango)
                  (@ (gnu packages stackage ghc-8.10 stage019)
                     haskell-8.10-haskell-gi)
                  (@ (gnu packages stackage ghc-8.10 stage006)
                     haskell-8.10-haskell-gi-base)
                  (@ (gnu packages stackage ghc-8.10 stage000)
                     haskell-8.10-haskell-gi-overloading)
                  (@ (gnu packages pkg-config) %pkg-config)))
    (propagated-inputs (list (@ (gnu packages pcre) pcre)
                             (@ (gnu packages compression) zlib)))
    (home-page "https://github.com/haskell-gi/haskell-gi")
    (synopsis "Gtk bindings")
    (description "Bindings for Gtk, autogenerated by haskell-gi.")
    (license (license "FSDG-compatible" "LGPL" ""))))

haskell-8.10-gi-gtk

(define-public haskell-8.10-hasql-notifications
  (package
    (name "haskell-8.10-hasql-notifications")
    (version "0.2.0.0")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/hasql-notifications/hasql-notifications-"
                    version ".tar.gz"))
              (sha256
               (base32
                "1zizvdvhb0nd126k24j4k62lzkx3qh1vp4976f2n7ri7ga5y6cxi"))))
    (properties `((upstream-name . "hasql-notifications") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #f
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)))
    (outputs (list "out" "static" "doc"))
    (inputs (list (@ (gnu packages stackage ghc-8.10 stage001)
                     haskell-8.10-contravariant)
                  (@ (gnu packages stackage ghc-8.10 stage023)
                     haskell-8.10-hasql)
                  (@ (gnu packages stackage ghc-8.10 stage024)
                     haskell-8.10-hasql-pool)
                  (@ (gnu packages stackage ghc-8.10 stage006)
                     haskell-8.10-postgresql-libpq)))
    (propagated-inputs (list (@ (gnu packages pcre) pcre)
                             (@ (gnu packages databases) postgresql)))
    (home-page "https://github.com/diogob/hasql-notifications")
    (synopsis "LISTEN/NOTIFY support for Hasql")
    (description
     "Use PostgreSQL Asynchronous notification support with your Hasql Types.")
    (license license:bsd-3)))

haskell-8.10-hasql-notifications

(define-public haskell-8.10-hasql-optparse-applicative
  (package
    (name "haskell-8.10-hasql-optparse-applicative")
    (version "0.3.0.8")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/hasql-optparse-applicative/hasql-optparse-applicative-"
                    version ".tar.gz"))
              (sha256
               (base32
                "1yx56vi1dpymxk5c3rkk74bbghcxfp6x333xn2j4x2ls38676dvg"))))
    (properties `((upstream-name . "hasql-optparse-applicative")
                  (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #t
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)))
    (outputs (list "out" "static" "doc"))
    (inputs (list (@ (gnu packages stackage ghc-8.10 stage000)
                     haskell-8.10-base-prelude)
                  (@ (gnu packages stackage ghc-8.10 stage023)
                     haskell-8.10-hasql)
                  (@ (gnu packages stackage ghc-8.10 stage024)
                     haskell-8.10-hasql-pool)
                  (@ (gnu packages stackage ghc-8.10 stage003)
                     haskell-8.10-optparse-applicative)))
    (propagated-inputs (list (@ (gnu packages pcre) pcre)
                             (@ (gnu packages databases) postgresql)))
    (home-page "https://github.com/sannsyn/hasql-optparse-applicative ")
    (synopsis "\"optparse-applicative\" parsers for \"hasql\"")
    (description "")
    (license license:expat)))

haskell-8.10-hasql-optparse-applicative

(define-public haskell-8.10-network-messagepack-rpc-websocket
  (package
    (name "haskell-8.10-network-messagepack-rpc-websocket")
    (version "0.1.1.1")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/network-messagepack-rpc-websocket/network-messagepack-rpc-websocket-"
                    version ".tar.gz"))
              (sha256
               (base32
                "0adkav3nl7ghbx2r7dx83ki6m397clxaw37s54ivnkxydqscjv06"))))
    (properties `((upstream-name . "network-messagepack-rpc-websocket")
                  (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #t
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)))
    (outputs (list "out" "static" "doc"))
    (inputs (list (@ (gnu packages stackage ghc-8.10 stage002)
                     haskell-8.10-QuickCheck)
                  (@ (gnu packages stackage ghc-8.10 stage001)
                     haskell-8.10-async)
                  (@ (gnu packages stackage ghc-8.10 stage014)
                     haskell-8.10-data-msgpack)
                  (@ (gnu packages stackage ghc-8.10 stage014)
                     haskell-8.10-envy)
                  (@ (gnu packages stackage ghc-8.10 stage006)
                     haskell-8.10-hspec)
                  (@ (gnu packages stackage ghc-8.10 stage005)
                     haskell-8.10-hspec-discover)
                  (@ (gnu packages stackage ghc-8.10 stage015)
                     haskell-8.10-network-messagepack-rpc)
                  (@ (gnu packages stackage ghc-8.10 stage023)
                     haskell-8.10-skews)
                  (@ (gnu packages stackage ghc-8.10 stage008)
                     haskell-8.10-websockets)
                  (@ (gnu packages stackage ghc-8.10 stage024)
                     haskell-8.10-wss-client)))
    (propagated-inputs (list (@ (gnu packages xorg) libpthread-stubs)
                             (@ (gnu packages pcre) pcre)
                             (@ (gnu packages compression) zlib)))
    (home-page
     "https://github.com/iij-ii/direct-hs/tree/master/network-messagepack-rpc-websocket")
    (synopsis "WebSocket backend for MessagePack RPC")
    (description "WebSocket backend for \"network-messagepack-rpc\"")
    (license license:bsd-3)))

haskell-8.10-network-messagepack-rpc-websocket

(define-public haskell-8.10-postgrest
  (package
    (name "haskell-8.10-postgrest")
    (version "7.0.1")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/postgrest/postgrest-" version
                    ".tar.gz"))
              (sha256
               (base32
                "1cn69dinfv3y8ymsa364b9b0ly3dg80and902gamymb9v89jpsgf"))))
    (properties `((upstream-name . "postgrest") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #f
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list "-f-failonwarn")
       #:cabal-revision
       ("6" "0kkhkz1bmgc1p0yry24fhc4a3s9w28wg6gxai0cggvalbz8c4pc4")))
    (outputs (list "out" "static" "doc"))
    (inputs (list (@ (gnu packages stackage ghc-8.10 stage009)
                     haskell-8.10-HTTP)
                  (@ (gnu packages stackage ghc-8.10 stage003)
                     haskell-8.10-Ranged-sets)
                  (@ (gnu packages stackage ghc-8.10 stage013)
                     haskell-8.10-aeson)
                  (@ (gnu packages stackage ghc-8.10 stage002)
                     haskell-8.10-ansi-wl-pprint)
                  (@ (gnu packages stackage ghc-8.10 stage015)
                     haskell-8.10-auto-update)
                  (@ (gnu packages stackage ghc-8.10 stage000)
                     haskell-8.10-base64-bytestring)
                  (@ (gnu packages stackage ghc-8.10 stage001)
                     haskell-8.10-case-insensitive)
                  (@ (gnu packages stackage ghc-8.10 stage013)
                     haskell-8.10-cassava)
                  (@ (gnu packages stackage ghc-8.10 stage005)
                     haskell-8.10-configurator-pg)
                  (@ (gnu packages stackage ghc-8.10 stage001)
                     haskell-8.10-contravariant)
                  (@ (gnu packages stackage ghc-8.10 stage002)
                     haskell-8.10-contravariant-extras)
                  (@ (gnu packages stackage ghc-8.10 stage011)
                     haskell-8.10-cookie)
                  (@ (gnu packages stackage ghc-8.10 stage014)
                     haskell-8.10-either)
                  (@ (gnu packages stackage ghc-8.10 stage001)
                     haskell-8.10-gitrev)
                  (@ (gnu packages stackage ghc-8.10 stage023)
                     haskell-8.10-hasql)
                  (@ (gnu packages stackage ghc-8.10 stage024)
                     haskell-8.10-hasql-pool)
                  (@ (gnu packages stackage ghc-8.10 stage024)
                     haskell-8.10-hasql-transaction)
                  (@ (gnu packages stackage ghc-8.10 stage000)
                     haskell-8.10-heredoc)
                  (@ (gnu packages stackage ghc-8.10 stage014)
                     haskell-8.10-http-types)
                  (@ (gnu packages stackage ghc-8.10 stage018)
                     haskell-8.10-insert-ordered-containers)
                  (@ (gnu packages stackage ghc-8.10 stage015)
                     haskell-8.10-interpolatedstring-perl6)
                  (@ (gnu packages stackage ghc-8.10 stage019)
                     haskell-8.10-jose)
                  (@ (gnu packages stackage ghc-8.10 stage017)
                     haskell-8.10-lens)
                  (@ (gnu packages stackage ghc-8.10 stage018)
                     haskell-8.10-lens-aeson)
                  (@ (gnu packages stackage ghc-8.10 stage006)
                     haskell-8.10-network)
                  (@ (gnu packages stackage ghc-8.10 stage008)
                     haskell-8.10-network-uri)
                  (@ (gnu packages stackage ghc-8.10 stage003)
                     haskell-8.10-optparse-applicative)
                  (@ (gnu packages stackage ghc-8.10 stage002)
                     haskell-8.10-protolude)
                  (@ (gnu packages stackage ghc-8.10 stage003)
                     haskell-8.10-regex-tdfa)
                  (@ (gnu packages stackage ghc-8.10 stage014)
                     haskell-8.10-retry)
                  (@ (gnu packages stackage ghc-8.10 stage001)
                     haskell-8.10-scientific)
                  (@ (gnu packages stackage ghc-8.10 stage019)
                     haskell-8.10-swagger2)
                  (@ (gnu packages stackage ghc-8.10 stage012)
                     haskell-8.10-unordered-containers)
                  (@ (gnu packages stackage ghc-8.10 stage001)
                     haskell-8.10-vector)
                  (@ (gnu packages stackage ghc-8.10 stage015)
                     haskell-8.10-wai)
                  (@ (gnu packages stackage ghc-8.10 stage016)
                     haskell-8.10-wai-cors)
                  (@ (gnu packages stackage ghc-8.10 stage018)
                     haskell-8.10-wai-extra)
                  (@ (gnu packages stackage ghc-8.10 stage021)
                     haskell-8.10-wai-middleware-static)
                  (@ (gnu packages stackage ghc-8.10 stage019)
                     haskell-8.10-warp)))
    (propagated-inputs (list (@ (gnu packages xorg) libpthread-stubs)
                             (@ (gnu packages pcre) pcre)
                             (@ (gnu packages databases) postgresql)
                             (@ (gnu packages compression) zlib)))
    (home-page "https://postgrest.org")
    (synopsis "REST API for any Postgres database")
    (description
     "Reads the schema of a PostgreSQL database and creates RESTful routes
for the tables and views, supporting all HTTP verbs that security
permits.")
    (license license:expat)))

haskell-8.10-postgrest

(define-public haskell-8.10-serverless-haskell
  (package
    (name "haskell-8.10-serverless-haskell")
    (version "0.12.6")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/serverless-haskell/serverless-haskell-"
                    version ".tar.gz"))
              (sha256
               (base32
                "1gk0zlfivpppirsalgxa58p8silr7ll396ld4x986m015hwnf8nh"))))
    (properties `((upstream-name . "serverless-haskell") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #f
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)))
    (outputs (list "out" "static" "doc"))
    (inputs (list (@ (gnu packages stackage ghc-8.10 stage013)
                     haskell-8.10-aeson)
                  (@ (gnu packages stackage ghc-8.10 stage014)
                     haskell-8.10-aeson-casing)
                  (@ (gnu packages stackage ghc-8.10 stage022)
                     haskell-8.10-amazonka-core)
                  (@ (gnu packages stackage ghc-8.10 stage024)
                     haskell-8.10-amazonka-kinesis)
                  (@ (gnu packages stackage ghc-8.10 stage024)
                     haskell-8.10-amazonka-s3)
                  (@ (gnu packages stackage ghc-8.10 stage001)
                     haskell-8.10-case-insensitive)
                  (@ (gnu packages stackage ghc-8.10 stage015)
                     haskell-8.10-http-client)
                  (@ (gnu packages stackage ghc-8.10 stage014)
                     haskell-8.10-http-types)
                  (@ (gnu packages stackage ghc-8.10 stage007)
                     haskell-8.10-iproute)
                  (@ (gnu packages stackage ghc-8.10 stage017)
                     haskell-8.10-lens)
                  (@ (gnu packages stackage ghc-8.10 stage007)
                     haskell-8.10-safe-exceptions)
                  (@ (gnu packages stackage ghc-8.10 stage012)
                     haskell-8.10-unordered-containers)))
    (propagated-inputs (list (@ (gnu packages xorg) libpthread-stubs)
                             (@ (gnu packages pcre) pcre)
                             (@ (gnu packages compression) zlib)))
    (home-page "https://github.com/seek-oss/serverless-haskell#readme")
    (synopsis "Deploying Haskell code onto AWS Lambda using Serverless")
    (description
     "Utilities to help process the events from AWS Lambda when deployed with the serverless-haskell plugin.")
    (license license:expat)))

haskell-8.10-serverless-haskell

