;;; generated file
(define-module (gnu packages stackage ghc-8.10 stage026)
  #:use-module ((guix download))
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module ((guix packages)))
;;; see commit 1597613488
(define license (@@ (guix licenses) license))
;;; explicitly define which ghc to use
(define ghc (@ (gnu packages haskell) ghc-8.10))
;;; add another patch file location (see gnu/packages.scm for pretty original)
(define-syntax-rule (search-patches file-name ...)
 (parameterize
  (((@ (gnu packages) %patch-path) (map (lambda (directory) (string-append directory "/patches")) %load-path)))
  (list ((@@ (gnu packages) search-patch) file-name) ...)))
(define-public haskell-8.10-gi-dbusmenugtk3
  (package
    (name "haskell-8.10-gi-dbusmenugtk3")
    (version "0.4.10")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/gi-dbusmenugtk3/gi-dbusmenugtk3-"
                    version ".tar.gz"))
              (sha256
               (base32
                "1hq7v2lii8n6nn1dhdg42z2d3in8xahkhm6xk4hmfj7abzfghz7z"))))
    (properties `((upstream-name . "gi-dbusmenugtk3") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #t
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)))
    (outputs (list "out" "static" "doc"))
    (inputs (list (@ (gnu packages gtk) gtk+)
                  (@ (gnu packages stackage ghc-8.10 stage022)
                     haskell-8.10-gi-atk)
                  (@ (gnu packages stackage ghc-8.10 stage022)
                     haskell-8.10-gi-dbusmenu)
                  (@ (gnu packages stackage ghc-8.10 stage024)
                     haskell-8.10-gi-gdk)
                  (@ (gnu packages stackage ghc-8.10 stage023)
                     haskell-8.10-gi-gdkpixbuf)
                  (@ (gnu packages stackage ghc-8.10 stage020)
                     haskell-8.10-gi-glib)
                  (@ (gnu packages stackage ghc-8.10 stage021)
                     haskell-8.10-gi-gobject)
                  (@ (gnu packages stackage ghc-8.10 stage025)
                     haskell-8.10-gi-gtk)
                  (@ (gnu packages stackage ghc-8.10 stage019)
                     haskell-8.10-haskell-gi)
                  (@ (gnu packages stackage ghc-8.10 stage006)
                     haskell-8.10-haskell-gi-base)
                  (@ (gnu packages stackage ghc-8.10 stage000)
                     haskell-8.10-haskell-gi-overloading)
                  (@ (gnu packages gtk) libdbusmenu)
                  (@ (gnu packages pkg-config) %pkg-config)))
    (propagated-inputs (list (@ (gnu packages pcre) pcre)
                             (@ (gnu packages compression) zlib)))
    (home-page "https://github.com/haskell-gi/haskell-gi")
    (synopsis "DbusmenuGtk bindings")
    (description "Bindings for libdbusgtk3, autogenerated by haskell-gi.")
    (license (license "FSDG-compatible" "LGPL" ""))))

haskell-8.10-gi-dbusmenugtk3

(define-public haskell-8.10-gi-gtk-hs
  (package
    (name "haskell-8.10-gi-gtk-hs")
    (version "0.3.12")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/gi-gtk-hs/gi-gtk-hs-" version
                    ".tar.gz"))
              (sha256
               (base32
                "1ph9fq2lwa16pq68vkmp2843n0hjx89zfjmxs80lsv41bkvza8qy"))))
    (properties `((upstream-name . "gi-gtk-hs") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #t
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)))
    (outputs (list "out" "static" "doc"))
    (inputs (list (@ (gnu packages stackage ghc-8.10 stage000)
                     haskell-8.10-base-compat)
                  (@ (gnu packages stackage ghc-8.10 stage024)
                     haskell-8.10-gi-gdk)
                  (@ (gnu packages stackage ghc-8.10 stage023)
                     haskell-8.10-gi-gdkpixbuf)
                  (@ (gnu packages stackage ghc-8.10 stage020)
                     haskell-8.10-gi-glib)
                  (@ (gnu packages stackage ghc-8.10 stage021)
                     haskell-8.10-gi-gobject)
                  (@ (gnu packages stackage ghc-8.10 stage025)
                     haskell-8.10-gi-gtk)
                  (@ (gnu packages stackage ghc-8.10 stage006)
                     haskell-8.10-haskell-gi-base)))
    (propagated-inputs (list (@ (gnu packages pcre) pcre)
                             (@ (gnu packages compression) zlib)))
    (home-page "https://github.com/haskell-gi/haskell-gi")
    (synopsis
     "A wrapper for gi-gtk, adding a few more idiomatic API parts on top")
    (description
     "A wrapper for gi-gtk, adding a few more idiomatic API parts on top")
    (license (license "FSDG-compatible" "LGPL" ""))))

haskell-8.10-gi-gtk-hs

(define-public haskell-8.10-gtk-strut
  (package
    (name "haskell-8.10-gtk-strut")
    (version "0.1.3.0")
    (source (origin
              (method url-fetch)
              (uri (string-append
                    "mirror://hackage/package/gtk-strut/gtk-strut-" version
                    ".tar.gz"))
              (sha256
               (base32
                "19p3w1zvnaazfd01yy4cl00sl53xc7kqgqhsw7l3psadmwk6x4w1"))))
    (properties `((upstream-name . "gtk-strut") (hidden? . #f)))
    (build-system (@ (guix build-system haskell) haskell-build-system))
    (arguments
     `(#:tests? #t
       #:haskell ,ghc
       #:haddock? #t
       #:configure-flags (list)))
    (outputs (list "out" "static" "doc"))
    (inputs (list (@ (gnu packages stackage ghc-8.10 stage024)
                     haskell-8.10-gi-gdk)
                  (@ (gnu packages stackage ghc-8.10 stage025)
                     haskell-8.10-gi-gtk)))
    (propagated-inputs (list (@ (gnu packages pcre) pcre)
                             (@ (gnu packages compression) zlib)))
    (home-page "https://github.com/IvanMalison/gtk-strut#readme")
    (synopsis "Libary for creating strut windows with gi-gtk")
    (description
     "Please see the README on Github at <https://github.com/IvanMalison/gtk-strut#readme>")
    (license license:bsd-3)))

haskell-8.10-gtk-strut

